services:

  mongo: # mongoDB database service
    image: mongo:7
    container_name: chat-mongo
    ports:
      - "27017:27017" # map local port to container port
    volumes:
      - mongo_data:/data/db # persist database data

  backend: # node.js backend (API + Socket.IO)
    build: ./backend
    container_name: chat-backend
    ports:
      - "5014:5014" # backend runs on port 5014
    environment:
      PORT: 5014 # set server port inside container
      MONGO_URI: mongodb://mongo:27017/chatapp # connect to Mongo container
    depends_on:
      - mongo # start only after MongoDB is ready

  frontend: # react frontend served via Nginx
    build: ./frontend
    container_name: chat-frontend
    ports:
      - "8080:80" # access frontend via localhost:8080
    depends_on:
      - backend # nnsure backend is started first

volumes:
  mongo_data: # named volume for persistent Mongodb storage